python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
cd ../ddl-simulator
python main.py
cd ../RO-ddl-simulator
python main.py
